name: Rom_Download

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'ROM_URL'
        required: true
        default: ''
      ZIP_NAME:
        description: 'ZIP_NAME'
        required: true
        default: ''
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:   
      - name: Apt update...
        run: |
          sudo apt update 
          sudo apt install -y git wget git zip unzip curl axel
          
      - name: Download ROM‌‌...
        run: |
          cd $GITHUB_WORKSPACE/
          mkdir ./Download
          wget -U "Mozilla/5.0" ${{ github.event.inputs.ROM_URL }} -O "$GITHUB_WORKSPACE/Download/${{ github.event.inputs.ZIP_NAME }}"
          echo "zip_file: $(ls "$GITHUB_WORKSPACE/Download/")" >> $GITHUB_WORKSPACE/Download/1.txt
          
      - name: Upload to Release‌‌...
        uses: ncipollo/release-action@v1.8.0
        with:
          artifacts: "${{ github.workspace }}/Download/*"
          tag: "${{ github.event.inputs.ZIP_NAME }}_${{ env.BUILD_TIME }}"
          bodyFile: "$GITHUB_WORKSPACE/Download/1.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
